### ISSUE TITLE
Hotel Entity 피드백 요청

### ISSUE THREAD

**Issue by kyupid** [kyu-kim-kr/airbnb#24]
![2021-05-21_18-06-56](https://user-images.githubusercontent.com/59721293/119090256-815dce00-ba5f-11eb-8b7b-1d9a32e231ef.jpg)
![2021-05-21_18-12-38](https://user-images.githubusercontent.com/59721293/119090779-25e01000-ba60-11eb-90f9-7373e236f1f5.jpg)

**Comment by kyupid** [comment]
`is_oneroom`이 좀 헷갈릴수도 있는데 원룸이랑 집전체 선택하기로 했던거 boolean으로 넣은거에요 ㅋㅋㅋㅋ

**Comment by ellyheetov** [comment]
변수명은 
`review_number`보다는 `review_count`
`avatar_url`보다는 `image_url`
이 좋은 것같아요. 사실 상관없는 부분이기는 하지만요 😃

나머지는 저희가 논의 한 대로 잘 이루어 진 것 같아요!

DB 설계적인 부분에서는 
hotel에 대한 정보를 전체를 가져오는 것이 아니라, `id`, `title`, `reiview_star`, `review_number`와 같이 부분적으로 가져오는 부분 도 있으니, 테이블을 조금 더 분리하시면 더 좋을 것 같아요.

**Comment by jeonyeonkyu** [comment]
좌표값이  hotel에 포함되어 있으면 더 좋을것같아여
전체 리스트 좌표값을 지도에 뿌려줘야해서요..

**Comment by ellyheetov** [comment]
> 좌표값이 hotel에 포함되어 있으면 더 좋을것같아여
전체 리스트 좌표값을 지도에 뿌려줘야해서요..

이부분은 지도에 뿌려줄때 따로 요청하면 되지 않나요?????

**Comment by jeonyeonkyu** [comment]
> > 좌표값이 hotel에 포함되어 있으면 더 좋을것같아여
> > 전체 리스트 좌표값을 지도에 뿌려줘야해서요..
> 
> 이부분은 지도에 뿌려줄때 따로 요청하면 되지 않나요?????

그렇게되면 하나의 hotel 아이디당 하나씩 요청을 해야할까요?
제가 잘 몰라서 ㅠ

**Comment by kyupid** [comment]
@jeonyeonkyu
제가 다이어그램을 캡쳐해서 보여드려가지구 괜한 혼란을 드린거같아요😅
해당 API에 대해서 좌표값 불러오도록 코드에서 만들예정입니다!
네이밍은 괜찮은가요?

**Comment by jeonyeonkyu** [comment]
넵 좋습니다~

**Comment by kyupid** [comment]
@ellyheetov 
> 변수명은 review_number보다는 review_count
> avatar_url보다는 image_url
> 이 좋은 것같아요. 사실 상관없는 부분이기는 하지만요 😃

아 넵 확실히 review_number 보다는 review_count가 좋아보여요!
avatar_url 은 한국어로는 "대표이미지" 라는 뜻에서 그렇게 이름을 지었어요 ㅠ.ㅠ (사실 깃헙Oauth에서 유저정보가져오면 avatar_url 이라고 되어있더라구요 ㅎㅎ) 아니면 profile_image_url 이라고하는것도 좋을거같긴한데 지역목록불러올때 사진이랑도 어울리는 네이밍인가 고민이되서..

> 나머지는 저희가 논의 한 대로 잘 이루어 진 것 같아요!

저희 의논한대로 됐다니 다행이네요!

> DB 설계적인 부분에서는
hotel에 대한 정보를 전체를 가져오는 것이 아니라, id, title, reiview_star, review_number와 같이 부분적으로 가져오는 부분 도 있으니, 테이블을 조금 더 분리하시면 더 좋을 것 같아요.

확실히 더 쪼개는 게 맞긴한데, 한테이블에 넣어서 DTO로 쪼개는게 제 취향에 더 맞더라구요 ㅎㅎ 그래서 일단은 이렇게 해보려고합니다.. (취향이 안티패턴일 수도 있지만..😅)
