### ISSUE TITLE
지도 API 수정요청

### ISSUE THREAD

**Issue by jeonyeonkyu** [kyu-kim-kr/airbnb#62]
### GET현재 위치 주변 숙소들 리스트 호출 API 

- 지도요청은 이것 사용

### response에 추가될 데이터

 ```javascript
 const data = {
  "x": 37,
  "y": 127,
  "maximumOccupancy": 8,
  "numberOfBeds": 2,
  "numberOfBathrooms": 1,
  "oneroom": false,
  "location": "서초구??(굳이 없어도됨)" 
}
```

- 현재 데이터에 추가해서 넣어주시면 됩니다 감사합니다~~

- location은 
![image](https://user-images.githubusercontent.com/61257242/120280905-411a0d80-c2f3-11eb-9668-ab6971351507.png)
 - 이것때문에 필요했는데
 - 작업하기 복잡하거나 시간여유가 없으시다면 빼주셔도 됩니다 프론트에서 임의로 넣어도 무방할 것같아요

**Comment by kyupid** [comment]
#63 
#64
