### ISSUE TITLE
mock 서버의 수명이 다한것 같습니다 ㅠ

### ISSUE THREAD

**Issue by jeonyeonkyu** [kyu-kim-kr/airbnb#65]
![image](https://user-images.githubusercontent.com/61257242/120374499-93d7e180-c354-11eb-968d-500cbec21648.png)

![image](https://user-images.githubusercontent.com/61257242/120374521-9c301c80-c354-11eb-88c7-1245763fea97.png)

- 제가 너무 많은 요청을 했나봐요 ㅠㅠ 수요일 아침에 다시 말씀드릴게여~

**Comment by kyupid** [comment]
오 이런거 처음보네요 ㅋㅋㅋㅋㅋ오늘 AWS로 배포해야겠어요~

**Comment by kyupid** [comment]
다른 서버 배포
