### ISSUE TITLE
iOS/FE 기획서 분석

### ISSUE THREAD

**Issue by kyupid** [kyu-kim-kr/airbnb#8]
어떤 API가 필요한지 요구사항에 따라서 겹치는 API들은 무엇인지 분석한다.

- [x] iOS
- [x] FE

---

Updated 2021.05.20 12:30

- [x] #9 개념적 데이터 모델링 (Entity, Attributes 만들어보기)
- [x] 팀원으로부터 피드백 받기
- [x] 컨펌된 것 바로 목서버로 배포

**Comment by kyupid** [comment]
Updated 2021.05.20 17:53 (11:30~12:30 회의한것 업뎃)

# [iOS 기획서](https://www.figma.com/proto/inTClwuq2Hr7E33JPIMKza/iOS_%EC%88%99%EC%86%8C%EC%98%88%EC%95%BD%EC%84%9C%EB%B9%84%EC%8A%A4?page-id=56:1424&node-id=56:1465&viewport=70,228,0.25&scaling=contain)

- [x] (2페이지)

1. 메인화면 API
  1-1. 검색바 눌렀을 때 나오는 결과 API (메인화면에서는 목록의 전체갯수혹은 limit을 정해서 반환)(여행지의 정보는 사진URL, 이름, 차로 얼마나걸리는지 거리)
  1-2. 큐레이션 배너 이미지 URL 정보 API (배경을 눌렀을때 / 여행아이디어 얻기 버튼 눌렀을 때) (생각안해도 됨)
  1-3. 가까운 여행지 둘러보기 목록 API
  1-4. 위시리스트 API, 저장, 삭제 API까지
  1-5. 로그인 API (나중에 물어보겠음)

- [x] (3페이지)

2. 검색바 API
  2-1. 검색바 눌렀을때 근처의 인기여행지 API (1-1-1, 1-1-3 API와 겹침)
  2-2. 검색에 따른 자동완성 리스트 APO (ElasticSearch)(iOS같은 경우엔 iOS단에서 해결할수있다/서버에요청안해도됨) (옵션)
  2-3. 검색어 초기화하고 근처의 인기 여행지 리스트가 다시 표시 API (2-2-1 API와 겹침)(필요없을듯..?)
  2-4. 여행지 리스트 중에서 원하는 여행지를 클릭했을때 불러올 정보 API (위치=여행지이름)

- [x] (4페이지)

3. 숙소찾기 (달력/날짜) API
  3-1. 백엔드랑 관계없음
  3-2. 요금을 누르면 어떤 정보가 필요한지 물어봐야할듯 어쩃든 모든 요금정보가 필요하니 위치에따른 모든 숙소의 가격정보가 필요
  3-3. 지우기눌렀을때는 어떻게 작동하는거지? (엘리가 생각할때 iOS기획서에서 7페이지까지넘어가는데, 검색버튼을 누를때까지 서버와 뭔가 통신이 불필요할거같음)
  3-4. 위치 리스트 표시 API

`다음`을 눌렀을 때 설정한 모든 정보를 한 Entity에 저장 해야함. (위치,체크인날짜/체크아웃날짜,요금,인원) Entity 이름을 뭐라고 할까?

- [x] (5페이지)

백엔드 서버와 통신할 것은 없어보임

- [x] **(6페이지)**

검색할때 가격범위를 지정하는 페이지인데, 이건 어떤 API가 필요할지 상의해봐야할거같다. (3-3-2와 겹침) (비모:인원과 위치에 따른 숙소가 얼마나 있는지 보내면 된다)
(엘리: 가격정보를 부를떄 위체 따른 숙소가 얼마나 있는지만 보내면된다? (숙소에는 가격이포함되어있다))
(엘리: 제주도라는 위치가 있다면 제주도에 대한 숙소들에 대한 가격을 배열로 반환)

(엘리: 숙소 데이터 몇개라도 넣어주세요)
일단은 전부 숙소가 공실이라고 생각하고, 가격변동도 없다라고 생각하면 되는데,
데이터를 수동으로 삽입,수정할때 예약된 숙소도 생각해보기.


- [x] (7페이지)

인원 정해주는 페이지, 백엔드와 통신할 것은 없어보인다? (요금,검색 버튼에서만 백엔드랑 통신하는듯?)

- [ ] (8페이지)

4. 숙소찾기 조건에 맞는 검색결과 API
  4-1. 입력했던 위치, 날짜 그리고 게스트 명수가 나와야하는 API (4페이지 확인)
  4-2. 숙소와 연결된 하트 표시가 있고, 그 하트를 누르면 위시리스트에 저장되는 API (3-3-4 리스트와 동일)
  4-3. 지도 펩 버튼을 누르면 검색결과를 지도에서 볼 수 있다. (뭐가 필요할지 모르겠음 상의해봐야함)
  4-4. 지우기 버튼을 누르면 검색결과 초기화 API (3-3-3과 동일한 API)

- [ ] (9페이지)

5. 지도에 표시되는 범위에 따라서 숙소들 리스트를 만들어주는 API (어떻게해야할지 모르겠음)
  5-1. 지도 내에 숙소들이 1박당 가격으로 나옴..
  5-2. 해당 지도에 보이는 숙소들 리스트가 지도에서 가로로
  5-3. 해당 지도에 보이는 숙소들 리스트가 세로로 (5-5-2와 같은 API)

- [ ] (10페이지)

6. 숙소 상세 페이지 API (밑에 나열한 리스트들을 한꺼번에 Response)
  6-1. 대표이미지와 그냥이미지의 URL들이 담긴 리스트
  6-2. 뒤로 버튼 누를시 검색 리스트 API (8페이지에서 구현한 API)
  6-3. 숙소에 대한 정보가 담긴 Entity
  6-4. 4-4-1과 동일한 Entity

- [ ] (11페이지)

4-4-1과 동일한 Entity..여기서 입력해주면 그 Entity에 저장

- [ ] (12페이지)

7. 최종 숙소 예약 API
  7-1. 일정,인원수에 따라 가격정보...이건 어디서해줘야할지 모르겠는데 상의가 필요할듯.
  7-2. 예약을 누르면 예약 목록에 담기는 API

- [ ] (13페이지)

8. 숙소 예약 상세 페이지 API (취소가능한 API)
  8-1. 예약한 숙소에대한 간략한 정보가나옴 (원래있던 API 재사용 4-4-1 동일)
  8-2. 예약 취소를 누르면 예약목록에서 지우는 API

- [ ] (14페이지)

9. 위시리스트 하트 눌러서 담았던 리스트 호출 API
  9-1. 하트를 다시 누르면 위시리스트에서 해당숙소가 제거되는 API

**Comment by kyupid** [comment]
FE 기획서 읽어봤는데 iOS 기획서에서 분석한 API들과 전부 겹치는 내용

**Comment by kyu-kim-kr** [comment]
2021.05.20 오전1130~1230 회의 후 기록

# [iOS 기획서](https://www.figma.com/proto/inTClwuq2Hr7E33JPIMKza/iOS_%EC%88%99%EC%86%8C%EC%98%88%EC%95%BD%EC%84%9C%EB%B9%84%EC%8A%A4?page-id=56:1424&node-id=56:1465&viewport=70,228,0.25&scaling=contain)

(2페이지)
1. 메인화면 API
  1-1. 검색바 눌렀을 때 나오는 결과 API (메인화면에서는 목록의 전체갯수혹은 limit을 정해서 반환)(여행지의 정보는 사진URL, 이름, 차로 얼마나걸리는지 거리)
  1-2. 큐레이션 배너 이미지 URL 정보 API (배경을 눌렀을때 / 여행아이디어 얻기 버튼 눌렀을 때) (생각안해도 됨)
  1-3. 가까운 여행지 둘러보기 목록 API
  1-4. 위시리스트 API, 저장, 삭제 API까지
  1-5. 로그인 API (나중에 물어보겠음)

(3페이지)
2. 검색바 API
  2-1. 검색바 눌렀을때 근처의 인기여행지 API (1-1-1, 1-1-3 API와 겹침)
  2-2. 검색에 따른 자동완성 리스트 APO (ElasticSearch)(iOS같은 경우엔 iOS단에서 해결할수있다/서버에요청안해도됨) (옵션)
  2-3. 검색어 초기화하고 근처의 인기 여행지 리스트가 다시 표시 API (2-2-1 API와 겹침)(필요없을듯..?)
  2-4. 여행지 리스트 중에서 원하는 여행지를 클릭했을때 불러올 정보 API (위치=여행지이름)

(4페이지)
3. 숙소찾기 (달력/날짜) API
  3-1. 백엔드랑 관계없음
  3-2. 요금을 누르면 어떤 정보가 필요한지 물어봐야할듯 어쩃든 모든 요금정보가 필요하니 위치에따른 모든 숙소의 가격정보가 필요
  3-3. 지우기눌렀을때는 어떻게 작동하는거지? (엘리가 생각할때 iOS기획서에서 7페이지까지넘어가는데, 검색버튼을 누를때까지 서버와 뭔가 통신이 불필요할거같음)
  3-4. 위치 리스트 표시 API

`다음`을 눌렀을 때 설정한 모든 정보를 한 Entity에 저장 해야함. (위치,체크인날짜/체크아웃날짜,요금,인원) Entity 이름을 뭐라고 할까?

(5페이지)
백엔드 서버와 통신할 것은 없어보임

**(6페이지)**가격
검색할때 가격범위를 지정하는 페이지인데, 이건 어떤 API가 필요할지 상의해봐야할거같다. (3-3-2와 겹침) (비모:인원과 위치에 따른 숙소가 얼마나 있는지 보내면 된다)
(엘리: 가격정보를 부를떄 위체 따른 숙소가 얼마나 있는지만 보내면된다? (숙소에는 가격이포함되어있다))
(엘리: 제주도라는 위치가 있다면 제주도에 대한 숙소들에 대한 가격을 배열로 반환)

(엘리: 숙소 데이터 몇개라도 넣어주세요)
일단은 전부 숙소가 공실이라고 생각하고, 가격변동도 없다라고 생각하면 되는데,
데이터를 수동으로 삽입,수정할때 예약된 숙소도 생각해보기.

숙소: 위치,요금,인원,체크인/체크아웃
totalPrice
checkIn
checkOut


숙소DTO안에 PriceDTO가 들어간다



(7페이지)
인원 정해주는 페이지, 백엔드와 통신할 것은 없어보인다? (요금,검색 버튼에서만 백엔드랑 통신하는듯?)

(8페이지)
4. 숙소찾기 조건에 맞는 검색결과 API
  4-1. 입력했던 위치, 날짜 그리고 게스트 명수가 나와야하는 API (4페이지 확인)
  4-2. 숙소와 연결된 하트 표시가 있고, 그 하트를 누르면 위시리스트에 저장되는 API (3-3-4 리스트와 동일)
  4-3. 지도 펩 버튼을 누르면 검색결과를 지도에서 볼 수 있다. (뭐가 필요할지 모르겠음 상의해봐야함)
  4-4. 지우기 버튼을 누르면 검색결과 초기화 API (3-3-3과 동일한 API)

(9페이지)
5. 지도에 표시되는 범위에 따라서 숙소들 리스트를 만들어주는 API (어떻게해야할지 모르겠음)
  5-1. 지도 내에 숙소들이 1박당 가격으로 나옴..
  5-2. 해당 지도에 보이는 숙소들 리스트가 지도에서 가로로
  5-3. 해당 지도에 보이는 숙소들 리스트가 세로로 (5-5-2와 같은 API)

(10페이지)
6. 숙소 상세 페이지 API (밑에 나열한 리스트들을 한꺼번에 Response)
  6-1. 대표이미지와 그냥이미지의 URL들이 담긴 리스트
  6-2. 뒤로 버튼 누를시 검색 리스트 API (8페이지에서 구현한 API)
  6-3. 숙소에 대한 정보가 담긴 Entity
  6-4. 4-4-1과 동일한 Entity

(11페이지)
4-4-1과 동일한 Entity..여기서 입력해주면 그 Entity에 저장

(12페이지)
7. 최종 숙소 예약 API
  7-1. 일정,인원수에 따라 가격정보...이건 어디서해줘야할지 모르겠는데 상의가 필요할듯.
  7-2. 예약을 누르면 예약 목록에 담기는 API

(13페이지)
8. 숙소 예약 상세 페이지 API (취소가능한 API)
  8-1. 예약한 숙소에대한 간략한 정보가나옴 (원래있던 API 재사용 4-4-1 동일)
  8-2. 예약 취소를 누르면 예약목록에서 지우는 API

(14페이지)
9. 위시리스트 하트 눌러서 담았던 리스트 호출 API
  9-1. 하트를 다시 누르면 위시리스트에서 해당숙소가 제거되는 API

**Comment by kyupid** [comment]
1. Updated 2021.05.20 17:48 (엘리 컨펌)
2. Updated 2021.05.20 18:57 (비모 컨펌)

# iOS 기획서 기준 1~7페이지 

- Hotel // 숙소를 호텔이라고 명명
  - id // 고유 번호
  - totalPrice // 총 요금
  - checkIn
  - checkOut
  - numberOfGuests
  - locationName

- Location
  - locationName // 고유 여행지 이름
  - avatarUrl // location 사진url
  - distance // 차로 얼마나걸리는지 분단위, 예를 들어서 차에서 50분 거리 -> 50
 
- User
  - id // 깃헙계정에대한 고유번호 
  - userName // 깃헙아이디 예시: ellyheetov, jeonyeonkyu
  - avatarUrl // 프로필사진url
  - wishList[]

----

# 나 보기 좋으라고 작성한거

```
HotelDTO // 숙소를 어컴이라고 명명
  private Long id; // 고유 번호
  private int totalPrice; // 총 요금
  private String checkIn; // 체크인날짜
  private String checkOut; // 체크아웃날짜
  private int numberOfGuests; // 총 게스트 수
  private LocationDTO locationDTO; // LocationDTO의 `name`을 가져옴


LocationDTO (+부를때 여행지를 몇개까지부를건지)
  private String name; // 고유 여행지 이름
  private String avatarUrl; // 사진url
  private int distance; // 차로 얼마나걸리는지 분단위

UserDTO 
  private String userName; // 깃헙아이디 예시: ellyheetov, jeonyeonkyu)
  private Long id; // 깃헙계정에대한 고유번호
  private String avatarUrl; // 프로필사진url
  private WishListDTO wishListDTO;


WishListDTO
  private List<AccomDTO> accomDTO; // AccomDTO의 고유번호만 담아서 보관
```

 특정 DTO에 대한 리스트가 필요할 시에 `List`에 담아서 보내도록 할것임

 ---

 지금 생각나는 앞으로 생성할 DTO

 1. HotelDetailDTO
 2. HostDTO
 3. ReservedHotelListDTO (UserDTO에 속함)

**Comment by ellyheetov** [comment]
Date Type도 웬만하면 통일하려고 하거든요. 적어주셔서 감사합니다.

**Comment by ellyheetov** [comment]
`numberOfGuests` 도 이후에는 `adult`,`child`, `baby` 이런식으로 나누는 부분 고려하시면 좋을 것 같아요.

**Comment by ellyheetov** [comment]
`Accom` 이라는 DTO클래스명은 `Hotel`이 더 익숙한건 저만 그런걸까요 ㅎㅎ

**Comment by kyupid** [comment]
1. `numberOfGuests`외에 추가로 `adults`, `children`, `infants` 만들까요?
2. ㅎㅎHotel도 좋습니다!

**Comment by kyupid** [comment]
3. DataType 통일하려고 하신다는 말씀은 데이터타입도 앞에 명시해달라는 말씀이신가요~??

**Comment by ellyheetov** [comment]
> numberOfGuests외에 추가로 adults, children, infants 만들까요?

현재 기획서를 참고하면 인원을 성인, 어린이, 유아로 분리하지만 결국 보이는건 "게스트3명" 이러식이다 보니 아직은 `numberOfGuests`로 사용하면 충분한 것 같아요. 

 > DataType 통일하려고 하신다는 말씀은 데이터타입도 앞에 명시해달라는 말씀이신가요~??

"나 좋으라고 작성한거" 부분이 저희에게도 도움이 된다는 말 입니당 ㅎㅎ 
앞으로도 계속 저렇게 명시해 주시면 좋을 것같아요.

**Comment by ellyheetov** [comment]
Accom, Location, User 부분 확인 했습니다. 
iOS는 위와 같이 진행해 주시면 문제 없을 것 같습니다.

**Comment by kyupid** [comment]
@ellyheetov 아하 "나 좋으라고 작성한거" 도움이 된다는 말씀이셨군요. 넵넵 확인감사해요.
@jeonyeonkyu 비모도 확인해주시면 작성한거 토대로 Request/Response API 만들어서 Mock 서버 배포하겠습니다

**Comment by jeonyeonkyu** [comment]
numberOfGuests는 수용인원을 말하는건가요?

**Comment by kyupid** [comment]
맞습니다! 다른말로하자면 총 인원 / 총 고객수 입니다

**Comment by jeonyeonkyu** [comment]
게스트가 성인과 유아의 가격을 다르게 주신다고 하면 PriceOfGuestKinds도 필요할것같아요 ex) 성인 : 1만원, 유아 : 5천원
물론 게스트 가격으로 통일해도 상관 없습니다~

**Comment by kyupid** [comment]
아 수용인원이 아니라 Request할때 성인,유아 인원수 올리고난후에 총 인원수입니다

**Comment by kyupid** [comment]
> 게스트가 성인과 유아의 가격을 다르게 주신다고 하면 PriceOfGuestKinds도 필요할것같아요 ex) 성인 : 1만원, 유아 : 5천원
물론 게스트 가격으로 통일해도 상관 없습니다~

성인/유아에 따라서 가격을 다르게 주며는 기본 호텔이 가지고 있는 가격에서 특정 인원수보다 더 인원이 올라가면 가격을 올린다는 말씀이죠?

예를들어서 호텔가격: 1박 100,000원 / 2명까지
성인: 1만원
유아 5천원

3명부터 성인은 + 1만원 유아는 +5천원 맞나용?
ex) 성인3명 유아1명 -> 115,000원

**Comment by jeonyeonkyu** [comment]
> 맞습니다! 다른말로하자면 총 인원 / 총 고객수 입니다

이부분이 조금 애매하게 느껴지는데

한 숙소에 수용인원의 수라고 볼 수도있고 ex) 4명까지만 입장가능
한 숙소의 방이 남아 있는지를 확인 할수 있는  호텔의 방 개수로 볼 수 도 있는데 ex) 방이 5개고 2명이 예약했다고하면 3고객 입장가능

이렇게 두가지로 생각이 드는데 어떤거라고 보면 될까요?

**Comment by jeonyeonkyu** [comment]
> > 게스트가 성인과 유아의 가격을 다르게 주신다고 하면 PriceOfGuestKinds도 필요할것같아요 ex) 성인 : 1만원, 유아 : 5천원
> > 물론 게스트 가격으로 통일해도 상관 없습니다~
> 
> 성인/유아에 따라서 가격을 다르게 주며는 기본 호텔이 가지고 있는 가격에서 특정 인원수보다 더 인원이 올라가면 가격을 올린다는 말씀이죠?
> 
> 예를들어서 호텔가격: 1박 100,000원 / 2명까지
> 성인: 1만원
> 유아 5천원
> 
> 3명부터 성인은 + 1만원 유아는 +5천원 맞나용?
> ex) 성인3명 유아1명 -> 115,000원

넵 맞습니다~

**Comment by kyupid** [comment]
> 한 숙소에 수용인원의 수라고 볼 수도있고 ex) 4명까지만 입장가능

이 부분은 사실 iOS 기준으로 10페이지에 있어서 아직 언급하진 않았는데 나중에 필요할거같아요.

> 한 숙소의 방이 남아 있는지를 확인 할수 있는 호텔의 방 개수로 볼 수 도 있는데 ex) 방이 5개고 2명이 예약했다고하면 3고객 입장가능

Airbnb에 올라오는 숙소들은 전부 `하나의 방` 이라서, 호텔이라고 이름을 명명하긴 했지만, 방이 여러개라는 의미는 아니었습니다.

**Comment by jeonyeonkyu** [comment]
> > 한 숙소에 수용인원의 수라고 볼 수도있고 ex) 4명까지만 입장가능
> 
> 이 부분은 사실 iOS 기준으로 10페이지에 있어서 아직 언급하진 않았는데 나중에 필요할거같아요.
> 
> > 한 숙소의 방이 남아 있는지를 확인 할수 있는 호텔의 방 개수로 볼 수 도 있는데 ex) 방이 5개고 2명이 예약했다고하면 3고객 입장가능
> 
> Airbnb에 올라오는 숙소들은 전부 `하나의 방` 이라서, 호텔이라고 이름을 명명하긴 했지만, 방이 여러개라는 의미는 아니었습니다.

그 두개가 아니라면 numberOfGuests가 무엇을 의미하는지 잘 모르겠습니다 ㅠ

**Comment by kyupid** [comment]
아하! 잠시만요 비모 FE기획서에서 numberOfGuests가 무엇을 의미하려고 했는지 스샷따오겠습니다

**Comment by kyupid** [comment]
![2021-05-20_21-13-37](https://user-images.githubusercontent.com/59721293/118952723-481a5500-b9b0-11eb-9582-5a5f92c1be20.jpg)
빨간박스로 체크되어있는 부분이 `numberOfGuests`를 의미하도록 생각했습니다 :)

**Comment by jeonyeonkyu** [comment]
> ![2021-05-20_21-13-37](https://user-images.githubusercontent.com/59721293/118952723-481a5500-b9b0-11eb-9582-5a5f92c1be20.jpg)
> 빨간박스로 체크되어있는 부분이 `numberOfGuests`를 의미하도록 생각했습니다 :)

넵 이해했습니다 감사합니다~

**Comment by kyupid** [comment]
아 넵, 그럼 위에 적혀있는대로 수정사항 없이 그대로 진행하면 될까요?

**Comment by jeonyeonkyu** [comment]
> 아 넵, 그럼 위에 적혀있는대로 수정사항 없이 그대로 진행하면 될까요?

넵 좋습니다 저도 해보다가 수정사항 필요하면 말씀드리겠습니다

**Comment by kyupid** [comment]
related #21
